### ISSUE TITLE
terran_10_vs_10

### ISSUE THREAD

**Issue by Lin-c-x** [instadeepai/og-marl#43]
Where can i get the SMACv2 terran_10_vs_10 dataset? 
I cannot find it on hugging face.

**Comment by lbeyers** [comment]
Hi @Lin-c-x , thanks for the engagement, we are in the process of uploading it to huggingface and it will be available in the next day or so. As you will see from the histogram, the returns of the dataset are not so great, but that is true for all of the smac_v2 datasets we have at the moment.

**Comment by jcformanek** [comment]
[https://huggingface.co/datasets/InstaDeepAI/og-marl/tree/main/core/smac_v2](https://huggingface.co/datasets/InstaDeepAI/og-marl/tree/main/core/smac_v2)
