### ISSUE TITLE
Can't get data in baselines-code branch

### ISSUE THREAD

**Issue by ZijunSong** [instadeepai/og-marl#50]
Hello!
I apologize for bothering you again, but I am currently trying to run the code from the baselines-code branch. Following your instructions, I successfully set up the environment. However, when I run main.py, I noticed that the dataset path in offline_dataset.py is not accessible.
Could you please clarify whether the path has been changed, or if there might be an issue on my end? Additionally, I would like to know if I can still access your dataset.
Thank you for your assistance!

**Comment by jcformanek** [comment]
Hi there, all the baseline code should now be on the main branch. 

Can you tell me exactly which datasets you want to run? Are you talking about the ones from other authors? You can see all the download links in this file: `og_marl/vault_utils/download_vault.py`

You can also download the datasets from HuggingFace: [https://huggingface.co/datasets/InstaDeepAI/og-marl](https://huggingface.co/datasets/InstaDeepAI/og-marl)

**Comment by ZijunSong** [comment]
Thank you for your help!
