### ISSUE TITLE
How can I get the metric **win rate**?

### ISSUE THREAD

**Issue by ZijunSong** [instadeepai/og-marl#51]
Hello!
I apologize for bothering you again. I am trying to run the code from the baselines-code branch. After I finished running(smac_v1_omiga environment), I noticed that the metric in the table (in the paper) is **win rate**. But the metric shown on wandb is **episode return**. How can I get the metric **win rate**?

<img width="677" alt="微信图片_20241031133029" src="https://github.com/user-attachments/assets/c765cf2c-6d0f-46a4-9814-d117a8185194">
<img width="681" alt="微信图片_20241031133328" src="https://github.com/user-attachments/assets/dbb942ee-e802-4df7-9810-30c865fbe57f">

Thank you for your assistance!

**Comment by jcformanek** [comment]
Hi there, sorry about that. I must have forgotten to add the win rate logging back in when I cleaned up the code. I have just made a commit to that branch to add win rate logging back. Please pull the latest changes on that branch and check it out.

**Comment by ZijunSong** [comment]
Thank you for your asistance! I am running the latest code. When I used the following configs `{'env': 'smac_v1_cfcql', 'scenario': '2s3z', 'dataset': 'Expert', 'system': 'iql+cql', 'seed': 42, 'exp': 'yebo'}`, I met an error:
```
File "/home/szj/og-marl-baselines-code/systems/idrqn_cql.py", line 56, in _tf_train_step  *
        actions = tf.cast(experience["actions"], "int32")[:,:,:,0]  # (B,T,N)
ValueError: Index out of range using input dim 3; input has only 3 dims for '{{node strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=7, ellipsis_mask=0, end_mask=7, new_axis_mask=0, shrink_axis_mask=8](Cast, strided_slice/stack, strided_slice/stack_1, strided_slice/stack_2)' with input shapes: [64,20,5], [4], [4], [4] and with computed input tensors: input[3] = <1 1 1 1>.
```
I have changed the line into `actions = tf.cast(experience["actions"], "int32")[:,:,:]` and the code is running smoothly. I hope my modifications have not changed the original intention of your code.
Thank you again for your kind help!
